# Generated by Django 6.0.5 on 2026-06-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Transport', 'Transport'), ('Shopping', 'Shopping'), ('Bills', 'Bills'), ('Subscription', 'Subscription'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
