# Generated by Django 6.0.5 on 2026-09-16 15:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('created_at', models.DateField(auto_now_add=True)),
                ('creation_time', models.TimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('updation_time', models.TimeField(auto_now=True)),
                ('budget_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Transport', 'Transport'), ('Shopping', 'Shopping'), ('Bills', 'Bills'), ('Subscription', 'Subscription'), ('Other', 'Other')], max_length=30)),
                ('limit_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly')], default='monthly', max_length=10)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='tracker.wallet')),
            ],
            options={
                'unique_together': {('wallet', 'category', 'period')},
            },
        ),
    ]
