# Generated by Django 6.0.5 on 2026-09-18 15:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_userprofile_welcome_email_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsGoalTransaction',
            fields=[
                ('created_at', models.DateField(auto_now_add=True)),
                ('creation_time', models.TimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('updation_time', models.TimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_transactions', to='tracker.savingsgoal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
