# Generated by Django 6.0.5 on 2026-07-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Freelance', 'Freelance'), ('Stipend', 'Stipend'), ('Scholarship', 'Scholarship'), ('Business Revenue', 'Business Revenue'), ('Food', 'Food'), ('Transport', 'Transport'), ('Shopping', 'Shopping'), ('Bills', 'Bills'), ('Subscription', 'Subscription'), ('Other', 'Other')], default='Other', max_length=30),
        ),
    ]
