# Generated by Django 6.0.5 on 2026-06-04 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_transaction_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='uuid',
            new_name='transaction_id',
        ),
    ]
